# Generated by Django 5.0 on 2024-01-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_remove_menuitem_featured_menuitem_inventory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
    ]
