# Generated by Django 5.0 on 2024-01-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0005_order_orderitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems", old_name="menu_item", new_name="menu_items",
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="LittleLemonAPI.order",
            ),
        ),
    ]
