# Generated by Django 5.0 on 2024-01-18 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0006_rename_menu_item_orderitems_menu_items_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart", unique_together={("menu_items", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="orderitems", unique_together={("order", "menu_items")},
        ),
    ]
