# Generated by Django 5.0 on 2024-01-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "LittleLemonAPI",
            "0008_remove_orderitems_cart_remove_orderitems_unit_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="date",),
    ]
