# Generated by Django 5.0 on 2024-01-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0010_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="delivery_personnel", new_name="delivery_crew",
        ),
    ]
